commands:
  daily: True
  beg: True
  fish: True
  hunt: True
  dig: True
  search: True
  highlow: True
  postmeme: True
  auto_buy: True
  
cooldowns:
  commands: 1
  timeout: 5

logging:
  debug: True
  warning: True